// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBlogPostFields {
  /** Title */
  title: string;

  /** URL Slug */
  urlSlug: string;

  /** date */
  date: string;

  /** body */
  body?: Document | undefined;
}

/** Generic, simple starter schema for blog posts */

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogPost";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IIdeaFields {
  /** Title */
  title: string;

  /** URL Slug */
  urlSlug: string;

  /** Date */
  date: string;

  /** Importance */
  importance: number;

  /** Content */
  content?: Document | undefined;

  /** Size Variations */
  sizeVariations?: "Third and Up" | "Half and Up" | "Full Only" | undefined;

  /** Image */
  image?: Asset | undefined;

  /** Image Size */
  imageSize?: "small" | "medium" | "large" | undefined;

  /** Image Placement */
  imagePlacement?: "Top" | "Bottom" | "Left" | "Right" | undefined;

  /** Image Scale Mode */
  imageScaleMode?: "fit" | "fill" | undefined;

  /** Related Ideas */
  relatedIdeas?: IIdea[] | undefined;
}

/** A singular idea that can be connected to other ideas */

export interface IIdea extends Entry<IIdeaFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "idea";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IIdeaPageFields {
  /** Title */
  title: string;

  /** date */
  date: string;

  /** URL Slug */
  urlSlug: string;

  /** Ideas */
  ideas?: IIdea[] | undefined;
}

/** A cluster of related ideas */

export interface IIdeaPage extends Entry<IIdeaPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "ideaPage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IImageFields {
  /** Title */
  title?: string | undefined;

  /** Name */
  name?: string | undefined;

  /** Description */
  description?: string | undefined;

  /** Asset */
  asset?: Asset | undefined;

  /** Digital Asset Manager Id */
  digitalAssetManagerId?: string | undefined;

  /** Figma File Id */
  figmaFileId?: string | undefined;

  /** Figma Node Id */
  figmaNodeId?: string | undefined;

  /** Figma User */
  figmaUser?: string | undefined;
}

export interface IImage extends Entry<IImageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "image";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IReadmeContentFields {
  /** Title */
  title?: string | undefined;

  /** Header */
  header?: string | undefined;

  /** Content */
  content?: string | undefined;

  /** Files */
  files?: Asset[] | undefined;

  /** Images */
  images?: IImage[] | undefined;
}

export interface IReadmeContent extends Entry<IReadmeContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "readmeContent";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IReadmePageFields {
  /** Title */
  title?: string | undefined;

  /** Name */
  name?: string | undefined;

  /** Content */
  content?:
    | (IImage | IReadmeContent | IReadmeProject | IReadmePage)[]
    | undefined;
}

export interface IReadmePage extends Entry<IReadmePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "readmePage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IReadmeProjectFields {
  /** Title */
  title?: string | undefined;

  /** Name */
  name?: string | undefined;

  /** Project Abbreviation */
  projectAbbreviation?: string | undefined;

  /** Table of Contents */
  tableOfContents?: boolean | undefined;

  /** Badges */
  badges?: Record<string, any> | undefined;

  /** Developer Emails */
  developerEmails?: string | undefined;

  /** NPM URL */
  npmUrl?: string | undefined;

  /** Repo URL */
  repoUrl?: string | undefined;

  /** Figma Widget URL */
  figmaWidgetUrl?: string | undefined;

  /** Production URL */
  productionUrl?: string | undefined;

  /** NonProduction URL */
  nonProductionUrl?: string | undefined;

  /** ## Description */
  description?: string | undefined;

  /** Content */
  content?:
    | (IImage | IReadmeContent | IReadmePage | IReadmeProject)[]
    | undefined;
}

export interface IReadmeProject extends Entry<IReadmeProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "readmeProject";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IUrlFields {
  /** Title */
  title?: string | undefined;

  /** URL */
  url?: string | undefined;
}

/** URL information */

export interface IUrl extends Entry<IUrlFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "url";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IWebComponentFields {
  /** Title */
  title?: string | undefined;

  /** Configuration */
  configuration?: Record<string, any> | undefined;

  /** Output */
  output?: string | undefined;

  /** References */
  references?: Entry<{ [fieldId: string]: unknown }>[] | undefined;
}

export interface IWebComponent extends Entry<IWebComponentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "webComponent";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "blogPost"
  | "idea"
  | "ideaPage"
  | "image"
  | "readmeContent"
  | "readmePage"
  | "readmeProject"
  | "url"
  | "webComponent";

export type IEntry =
  | IBlogPost
  | IIdea
  | IIdeaPage
  | IImage
  | IReadmeContent
  | IReadmePage
  | IReadmeProject
  | IUrl
  | IWebComponent;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
